package com.example.iruaco;

import java.util.ArrayList;

public class Questions {
    public String question,translated_question;

    public Questions (String question, String translated_question){
        this.question = question;
        this.translated_question = translated_question;
    }
    public static ArrayList <Questions> questions_list = new ArrayList <Questions>();

    public static void build_questions_list (String input_language) {
        String [] temp = French.clone();

        switch (input_language) {
            case "Arabic":
                temp = Arabic.clone();
                break;
            case "French":
                temp = French.clone();
                break;
            case "German":
                temp = German.clone();
                break;
            case "Spanish":
                temp = Spanish.clone();
                break;
            case "Twi":
                temp = Twi.clone();
                break;
        }
        questions_list.clear();

        for (int i =0; i<105; i++) {
            questions_list.add(new Questions(English[i],temp[i]));
        }
    }

    private static String English [] = {
     // Airport questions, index 0 to 14
            "Is there an airport shuttle?",
            "Where can I find the ATM?",
            "Do you speak english?",
            "Can I use your telephone?",
            "Where can I get a taxi?",
            "Where can I purchase a sim card?",
            "Where can I find a forex bureau?",
            "Can you help me find an english speaker?",
            "Is there a Hotel for this airport?",
            "Where is the medical service?",
            "Where is baggage claim?",
            "Where is the bathroom?",
            "Where is the gift shop?",
            "Where is customer service?",
            "Where is the main counter?",
     // Emergency questions, index 15 to 29
            "What is the number of the police?",
            "Can you help me call for security?",
            "Where is the closest hospital?",
            "What is the local EMT number here?",
            "Where is the closest police station?",
            "Where is the closest pharmacy?",
            "Where can I rent a car in the area?",
            "Do you have any allergies?",
            "Can you call me an ambulance?",
            "Where is the bathroom?",
            "Can you show me on the app?",
            "I am lost can you please help me?",
            "Do you speak English?",
            "Can you speak slower?",
            "Is there a 24/7 pharmacy in the area?",
            // Food questions, index 30 to 44
            "Where can I have breakfast?",
            "What type of food do you have?",
            "Do you have vegetarian options?",
            "Where's the closest restaurant?",
            "Do you accept foreign currency?",
            "Do you deliver?",
            "Where can I get Chinese cuisine?",
            "Do you have special offers?",
            "What are your fish options?",
            "Is there an ATM machine around?",
            "Where can I buy baby food",
            "Where can I purchase Fruits?",
            "Do you have eggs?",
            "Where can I buy pots and pans?",
            "What are your dessert options?",
    // health questions, index 45 to 59
            "Can you Speak English?",
            "What's the closest a Hospital around?",
            "Is there an ATM around here?",
            "Do you have a Doctor here?",
            "Is there a Doctor Around?",
            "Where can I see a pediatrician?",
            "Where can I get contact lenses?",
            "Is there an ambulance service?",
            "Where is the closest Pharmacy?",
            "Do you take credit cards?",
            "Where is the closest emergency center?",
            "Where can I buy medicine?",
            "Can you help me call a doctor?",
            "Is there an optician present?",
            "Where do I pay?",
    // leisure questions, index 60 to 74
            "Where can I get a guide?",
            "Is there a museum around?",
            "Is there a gallery around?",
            "Where is the closest mall?",
            "What are the places of attraction?",
            "Where can I get a taxi?",
            "Are there any beaches around?",
            "Where are the closest spa places?",
            "Can I get the receipt?",
            "Do you have any specials?",
            "Where do I get souvenirs here?",
            "Where is the closest cinema?",
            "What are the clubs around here?",
            "Do you speak english?",
            "Where is the ATM machine?",
    // lodging questions, index 75 to 89
            "Can I get a concierge?",
            "How do I make a reservation?",
            "Do you accept pets?",
            "What is your cancellation policy?",
            "What is your payment policy?",
            "Do you provide towels?",
            "Can I get an Iron?",
            "What is your firearms policy?",
            "Do you have a laundry service?",
            "When is the check-out time?",
            "Can I have a camp fire?",
            "Are pack and plays available?",
            "Can I get a smoking room?",
            "Can I get a non-smoking room?",
            "Are there handicapped rooms?",
    // transportation questions, 90 to 104
            "Where can I rent a car?",
            "What is the fastest route to use?",
            "Where is the nearest filling station?",
            "Where is the closest rest stop?",
            "Can you help me change a tyre?",
            "How much is the fare?",
            "Can I get the bus schedule?",
            "How long is this trip going to be?",
            "Where is the nearest Synagogue?",
            "Where is the nearest airport?",
            "Where can I get taxi?",
            "Can I have a helmet?",
            "Where is the nearest Church?",
            "Where is the nearest Mosque?",
            "Can I get the train schedule?"
    };
    private static String French [] = {
            // Airport questions, index 0 to 14
            "Y a-t-il une navette aéroport?",
            "Où puis-je trouver le guichet automatique?",
            "Parlez vous anglais?",
            "Puis-je utiliser votre téléphone?",
            "Où puis-je trouver un taxi?",
            "Où puis-je acheter une carte SIM?",
            "Où puis-je trouver un bureau de change?",
            "Pouvez-vous m'aider à trouver un anglophone?",
            "Y a-t-il un hôtel pour cet aéroport?",
            "Où est le service médical?",
            "Où est la récupération des bagages?",
            "Où se trouvent les toilettes?",
            "Où est la boutique de cadeaux?",
            "Où est le service client?",
            "Où est le comptoir principal?",
            // Emergency questions, index 15 to 29
            "Quel est le numéro de la police ?",
            "Pouvez-vous m'aider à appeler à la sécurité?",
            "Où est l'hôpital le plus proche?",
            "Quel est le numéro SAMU local ici?",
            "Où est le poste de police le plus proche?",
            "Où est la pharmacie la plus proche?",
            "Où puis-je louer une voiture dans la région?",
            "Avez-vous des allergies?",
            "Pouvez-vous m’appeler une ambulance?",
            "Où se trouvent les toilettes?",
            "Pouvez-vous me montrer sur l'application?",
            "Je suis perdu, pouvez-vous m'aider?",
            "Parlez-vous l’anglais?",
            "Pouvez-vous parler plus lentement?",
            "Y a-t-il une pharmacie ouverte?",
            // Food questions, index 30 to 44
            "Où puis-je prendre le petit déjeuner?",
            "Quel type de nourriture avez-vous?",
            "Avez-vous des options végétariennes?",
            "Quel est le restaurant le plus proche?",
            "Acceptez-vous les devises étrangères?",
            "Pouvez-vous livrer?",
            "Où puis-je trouver de la cuisine asiatique?",
            "Avez-vous des offres spéciales?",
            "Quelles sont vos options de poisson?",
            "Y a-t-il un guichet automatique dans les parages?",
            "Où puis-je acheter des aliments pour bébés",
            "Où puis-je acheter des fruits?",
            "Avez-vous des œufs?",
            "Où puis-je acheter des casseroles et des poêles?",
            "Quelles sont vos options de dessert?",
            // health questions, index 45 to 59
            "Pouvez-vous parler l’anglais?",
            "Quel est l'hôpital le plus proche?",
            "Y a-t-il un guichet automatique par ici?",
            "Il y a-t-il un docteur dans les alentours ?",
            "Y a-t-il un docteur ?",
            "Où puis-je voir un pédiatre?",
            "Où puis-je me procurer des lentilles de contact?",
            "Y a-t-il un service d'ambulance?",
            "Où est la pharmacie la plus proche?",
            "Prenez-vous les cartes de crédit?",
            "Où est le centre d'urgence le plus proche?",
            "Où puis-je acheter des médicaments?",
            "Pouvez-vous m'aider à appeler un médecin?",
            "Y a-t-il un opticien présent?",
            "Où est-ce que je paie?",
            // leisure questions, index 60 to 74
            "Où puis-je trouver un guide?",
            "Y a-t-il un musée dans les alentours?",
            "Y a-t-il une galerie dans les alentours?",
            "Où est le centre commercial le plus proche?",
            "Quels sont les lieux d'attraction?",
            "Où puis-je trouver un taxi?",
            "Y a-t-il des plages dans les alentours ?",
            "Où sont les spas les plus proches?",
            "Puis-je obtenir le reçu?",
            "Avez-vous un menu du jour?",
            "Où puis-je trouver des souvenirs ici?",
            "Où est le cinéma le plus proche?",
            "Quels sont les boites de nuits ici?",
            "Parlez vous l’anglais?",
            "Où est le guichet automatique?",
            // lodging questions, index 75 to 89
            "Puis-je obtenir un concierge?",
            "Comment faire une réservation?",
            "Acceptez-vous les animaux?",
            "Quelle est votre police d'annulation?",
            "Quelle est votre police de paiement?",
            "Fournissez-vous des serviettes?",
            "Puis-je obtenir un fer à repasser?",
            "Autorisez-vous les armes à feu?",
            "Avez-vous un service de blanchisserie?",
            "Quelle est l'heure de départ?",
            "Puis-je avoir un feu de camp dans votre jardin?",
            "Les packs et les jeux sont-ils disponibles?",
            "Puis-je avoir un fumoir?",
            "Puis-je avoir une chambre non-fumeur?",
            "Y a-t-il des chambres aux handicapés?",
            // transportation questions, 90 to 104
            "Où puis-je louer une voiture?",
            "Quel est l'itinéraire le plus rapide à utiliser?",
            "Où est la station-service la plus proche?",
            "Où est l'air de repos la plus proche?",
            "Pouvez-vous m'aider à changer un pneu?",
            "Combien c’est?",
            "Puis-je obtenir les horaires de bus?",
            "Combien de temps va durer ce voyage?",
            "Où est la synagogue la plus proche?",
            "Où est l'aéroport le plus proche?",
            "Où puis-je prendre un taxi?",
            "Puis-je avoir un casque?",
            "Où est l'église la plus proche?",
            "Où est la mosquée la plus proche?",
            "Puis-je obtenir les horaires des trains?"
    };
    private static String German[] = {
            // Airport questions, index 0 to 14
            "Gibt es einen Flughafentransfer?",
            "Wo finde ich den Geldautomaten?",
            "Sprichst du Englisch?",
            "Kann ich dein Telefon benutzen?",
            "Wo bekomme ich ein Taxi?",
            "Wo kann ich eine SIM-Karte kaufen?",
            "Wo finde ich ein Forex-Büro?",
            "Sprichst du Englisch?",
            "Gibt es ein Hotel für diesen Flughafen?",
            "Wo ist der medizinische Dienst?",
            "Wo ist die Gepäckausgabe?",
            "Wo ist die Toilette?",
            "Wo ist der Geschenkeladen?",
            "Wo ist Kundenservice?",
            "Wo ist der Hauptschalter?",
            // Emergency questions, index 15 to 29
            "Wie ist die Nummer der Polizei?",
            "Können Sie mir helfen, Sicherheit zu rufen?",
            "Wo ist das nächste Krankenhaus?",
            "Wie lautet die lokale EMT-Nummer hier?",
            "Wo ist die nächste Polizeistation?",
            "Wo ist die nächste Apotheke?",
            "Wo kann ich in der Umgebung ein Auto mieten?",
            "Hast du irgendwelche Allergien?",
            "Können Sie mich einen Krankenwagen nennen?",
            "Wo ist die Toilette?",
            "Kannst du es mir in der App zeigen?",
            "Ich bin verloren. Kannst du mir bitte helfen?",
            "Sprichst du Englisch?",
            "Kannst du langsamer sprechen?",
            "Gibt es eine 24/7-Apotheke in der Umgebung?",
            // Food questions, index 30 to 44
            "Wo kann ich frühstücken?",
            "Welche Art von Essen haben Sie?",
            "Haben Sie vegetarische Optionen?",
            "Was ist das nächste Restaurant?",
            "Akzeptieren Sie Fremdwährung?",
            "Können Sie liefern?",
            "Wo kann ich chinesische Küche bekommen?",
            "Haben Sie spezielle Angebote?",
            "Was sind Ihre Fischoptionen?",
            "Gibt es einen Geldautomaten?",
            "Wo kann ich Babynahrung kaufen?",
            "Wo kann ich Früchte kaufen?",
            "Hast du eier",
            "Wo kann ich Töpfe und Pfannen kaufen?",
            "Was sind Ihre Dessertoptionen?",
            // health questions, index 45 to 59
            "Sprechen Sie Englisch?",
            "Was ist das nächstgelegene Krankenhaus?",
            "Gibt es hier einen Geldautomaten?",
            "Haben Sie hier einen Arzt?",
            "Gibt es einen Arzt?",
            "Wo kann ich einen Kinderarzt aufsuchen?",
            "Wo kann ich Kontaktlinsen bekommen?",
            "Gibt es einen Rettungsdienst?",
            "Wo ist die nächste Apotheke?",
            "Do you take credit cards?",
            "Wo ist die nächste Notrufzentrale?",
            "Wo kann ich Medikamente kaufen?",
            "Können Sie mir helfen, einen Arzt zu rufen?",
            "Ist ein Optiker anwesend?",
            "Wo bezahle ich?",
            // leisure questions, index 60 to 74
            "Wo kann ich einen Führer bekommen?",
            "Gibt es ein Museum?",
            "Gibt es eine Galerie?",
            "Wo ist das nächste Einkaufszentrum?",
            "Was sind die Anziehungspunkte?",
            "Wo bekomme ich ein Taxi?",
            "Gibt es Strände in der Nähe?",
            "Wo sind die nächsten Wellnessplätze?",
            "Kann ich die Quittung bekommen?",
            "Hast du irgendwelche Specials?",
            "Woher bekomme ich hier Souvenirs?",
            "Wo ist das nächste Kino?",
            "Was sind die Clubs hier?",
            "Sprichst du Englisch?",
            "Wo ist der Geldautomat?",
            // lodging questions, index 75 to 89
            "Kann ich einen Concierge bekommen?",
            "Wie reserviere ich?",
            "Akzeptierst du Haustiere?",
            "Was ist Ihre Stornierungsbedingungen?",
            "Was ist Ihre Zahlungsrichtlinie?",
            "Stellen Sie Handtücher zur Verfügung?",
            "Kann ich ein Bügeleisen bekommen?",
            "Was ist Ihre Waffenpolitik?",
            "Haben Sie einen Wäscheservice?",
            "Was sind Check-In / Check-Out Zeiten? ",
            "Kann ich ein Lagerfeuer haben?",
            "Sind Pack und Spiele verfügbar?",
            "Kann ich ein Raucherzimmer bekommen?",
            "Kann ich ein Nichtraucherzimmer bekommen?",
            "Gibt es behindertengerechte Zimmer?",
            // transportation questions, 90 to 104
            "Wo kann ich ein Auto mieten?",
            "Was ist der schnellste Weg?",
            "Wo ist die nächste Tankstelle?",
            "Wo ist die nächste Raststätte?",
            "Können Sie mir helfen, einen Reifen zu wechseln?",
            "Wie viel kostet der Fahrpreis?",
            "Kann ich den Busfahrplan bekommen?",
            "Wie lange wird diese Reise dauern?",
            "Wo ist die nächste Synagoge?",
            "Wo ist der nächste Flughafen?",
            "Wo kann ich ein Taxi bekommen?",
            "Kann ich einen Helm haben?",
            "Wo ist die nächste Kirche?",
            "Wo ist die nächste Moschee?",
            "Kann ich den Zugfahrplan bekommen?"
    };
    private static String Spanish[] = {
            // Airport questions, index 0 to 14
            "¿Hay servicio de transporte al aeropuerto?",
            "¿Dónde puedo encontrar el cajero automático?",
            "¿Habla usted Inglés?",
            "¿Puedo usar tu teléfono?",
            "¿Donde puedo conseguir un taxi?",
            "¿Dónde puedo comprar una tarjeta SIM?",
            "¿Dónde puedo encontrar una oficina de divisas?",
            "¿Puedes ayudarme a encontrar un hablante de inglés?",
            "¿Hay un hotel para este aeropuerto?",
            "¿Dónde está el servicio médico?",
            "¿Dónde está el reclamo de equipaje?",
            "¿Dónde está el baño?",
            "¿Dónde está la tienda de regalos?",
            "¿Dónde está el servicio al cliente?",
            "¿Dónde está el mostrador principal?",
            // Emergency questions, index 15 to 29
            "¿Cuál es el número de la policía?",
            "¿Me pueden ayudar a pedir seguridad?",
            "¿Dónde está el hospital más cercano?",
            "¿Cuál es el número local de EMT aquí?",
            "¿Dónde está la estación de policía más cercana?",
            "¿Dónde está la farmacia más cercana?",
            "¿Dónde puedo alquilar un auto en el área?",
            "¿Tienes alguna alergia?",
            "¿Puedes llamarme una ambulancia?",
            "¿Dónde está el baño?",
            "¿Me puede mostrar en la aplicación?",
            "Estoy perdido, ¿puedes ayudarme?",
            "¿Habla usted Inglés?",
            "¿Puedes hablar más lento?",
            "¿Hay una farmacia 24/7 en el área?",
            // Food questions, index 30 to 44
            "¿Dónde puedo desayunar?",
            "¿Qué tipo de comida tienes?",
            "¿Tienes opciones vegetarianas?",
            "¿Cuál es el restaurante más cercano?",
            "¿Acepta moneda extranjera?",
            "¿Puedes entregar?",
            "¿Dónde puedo conseguir cocina china?",
            "¿Tienes ofertas especiales?",
            "¿Cuáles son tus opciones de pescado?",
            "¿Hay un cajero automático alrededor?",
            "¿Dónde puedo comprar comida para bebés?",
            "¿Dónde puedo comprar frutas?",
            "¿Tienes huevos?",
            "¿Dónde puedo comprar ollas y sartenes?",
            "¿Cuáles son tus opciones de postres?",
            // health questions, index 45 to 59
            "¿Puedes hablar ingles?",
            "¿Cuál es el hospital más cercano?",
            "¿Hay un cajero automático por aquí?",
            "¿Tienes un doctor aquí?",
            "¿Hay un doctor alrededor?",
            "¿Dónde puedo ver a un pediatra?",
            "¿Dónde puedo obtener lentes de contacto?",
            "¿Hay un servicio de ambulancia?",
            "¿Dónde está la farmacia más cercana?",
            "¿Aceptan tarjetas de crédito?",
            "¿Dónde está el centro de emergencias más cercano?",
            "¿Dónde puedo comprar medicamentos?",
            "¿Me pueden ayudar a llamar a un médico?",
            "¿Hay un óptico presente?",
            "¿Dónde lo pago?",
            // leisure questions, index 60 to 74
            "¿Dónde puedo obtener una guía?",
            "¿Hay un museo alrededor?",
            "¿Hay una galería alrededor?",
            "¿Dónde está el centro comercial más cercano?",
            "¿Cuáles son los lugares de atracción?",
            "¿Donde puedo conseguir un taxi?",
            "¿Hay alguna playa alrededor?",
            "¿Dónde están los lugares de spa más cercanos?",
            "¿Puedo obtener el recibo?",
            "¿Tienes alguna oferta especial?",
            "¿Dónde consigo recuerdos aquí?",
            "¿Dónde está el cine más cercano?",
            "¿Cuáles son los clubes por aquí?",
            "¿Habla usted Inglés?",
            "¿Dónde está el cajero automático?",
            // lodging questions, index 75 to 89
            "¿Puedo obtener un conserje?",
            "¿Cómo hago una reserva?",
            "¿Aceptan mascotas?",
            "¿Cuál es su política de cancelación?",
            "¿Cuál es su política de pago?",
            "¿Proporcionan toallas?",
            "¿Puedo obtener una plancha?",
            "What is your firearms policy?",
            "¿Tienes servicio de lavandería?",
            "¿Cuáles son los horarios de entrada / salida? ",
            "¿Puedo tener una fogata?",
            "¿Hay paquetes y juegos disponibles?",
            "¿Puedo conseguir una habitación para fumadores?",
            "¿Puedo obtener una habitación para no fumadores?",
            "¿Hay habitaciones accesibles para discapacitados?",
            // transportation questions, 90 to 104
            "¿Dónde puedo alquilar un coche?",
            "¿Cuál es la ruta más rápida de usar?",
            "¿Dónde está la estación de servicio más cercana?",
            "¿Dónde está la parada de descanso más cercana?",
            "¿Me pueden ayudar a cambiar un neumático?",
            "¿Cuanto es lo justo?",
            "¿Puedo obtener el horario del autobús?",
            "¿Cuánto durará este viaje?",
            "¿Dónde está la sinagoga más cercana?",
            "¿Dónde está el aeropuerto más cercano?",
            "¿Dónde puedo coger un taxi?",
            "¿Puedo tener un casco?",
            "¿Dónde está la iglesia más cercana?",
            "¿Dónde está la mezquita más cercana?",
            "¿Puedo obtener el horario del tren?"
    };
    private static String Twi[] = {
            // Airport questions, index 0 to 14
            "Awiamshen  bea yi wo car aa ede yen beko fie anaa?",
            "ATM machine no wo he?",
            "Wo te brofo kasa anaa?",
            "Me tumi afre obi wo wo tete phone no so anaa?",
            "Ehenfa na menya taxi?",
            "Enhenfa na menya sim card?",
            "Ehenfa na menya forex bureau?",
            "Wo be nya obi a ote brofo kasa ama me anaa?",
            "Airport yi wo hotel anaa?",
            "Ayaresabea no wo he?",
            "Ahenfa na ye be gye yen ndaka aa ye di firi akwan tuo mu no?",
            "Agware ne agyanan bea no wo he?",
            "Ehenfa na adeton fuo no wo?",
            "Airport aboafo no wo hene?",
            "Ehenfa na airport mpanin fuo no wo aa wobe tumi aboa me?",
            // Emergency questions, index 15 to 29
            "Ban bo fuo (polisi) number ye dien?",
            "Wo be tumi aboa me na mafre airport ban bo fuo no?",
            "Ayaresabea ben na eben ha?",
            "Number ben na menfre knosi Emergency Number fuo no so?",
            "Police station ben na eben ha?",
            "Pharmacy ben na eben ha?",
            "Ehenfa na me nya dropping?",
            "Biribi wo ho aa ene wo nipa dua engye anaa?",
            "Wo be tumi afre ambulance ama me?",
            "Agware ne agyanan bea no wo he?",
            "Wo be tumi a kyere me app no?",
            "Ma yera.  Wo be tumi aboa me anaa?",
            "Wo te brofo kasa anaa?",
            "Wo be tumi a akasa bokoo kakra anaa?",
            "Pharmacy bi wo aha a yoye adwuma anopa ko pim anadwo anaa?",
            // Food questions, index 30 to 44
            "Ehenfa na me tumi adidi anopa?",
            "Aduane ben na mo wo?",
            "Mo wo aduame ma vegetarians?",
            "Restaurant ben na eben ha?",
            "Mo gye amanone sika anaa?",
            "Mo be tumi de aduane no abre me wo me tena bea anaa?",
            "Ehenfa na menya Chinese aduane adi?",
            "Mo wo aduane tiriw bi aa me tumi adi anaa?",
            "Nsuo mu nam ben na mo wo?",
            "ATM machine bi ben ha anaa?",
            "Ehenfa na menya mmofra aduane ato wo ha?",
            "Ehenfa na menya ankaa, amango, kwedu ne nkekaho ato?",
            "Mo wo knosua?",
            "Ehenfa na menya nkyensee ato?",
            "Eden na mo wo aa mede be pepa maanum?",
            // health questions, index 45 to 59
            "Wo te brofo kasa anaa?",
            "Asipiti ben na eben ha?",
            "ATM machine bi ben ha anaa?",
            "Dokita wo ha anaa?",
            "Dokita no wo ha anaa?",
            "Ehenfa na menya dokita aa ohwe mmofra?",
            "Ehenfa na menya contact lenses?",
            "Ehenfa na menya ambulance?",
            "Pharmacy ben na eben ha?",
            "Mo gye credit card anaa?",
            "Emergency center bi ben aha anaa?",
            "Ehenfa na menya eduro ato?",
            "Wo be tumi afre dokita no ama me anaa?",
            "Mo wo dokita aa ohwe eni anaa?",
            "Ehenfa na me tua meka no?",
            // leisure questions, index 60 to 74
            "Ehenfa na menya obi aa obe kyere me krom?",
            "Mo wo museum wo aha anaa?",
            "Mo wo gallery wo aha anaa?",
            "Mo wo egwem wo aha anaa?",
            "Ehenfa na me tumi ako bo mmeeni akonhoma?",
            "Ehenfa na menya taxi?",
            "Ehenfa na me tumi ako gware epo?",
            "Mo wo spa wo ahanom beebi?",
            "Wo be tumi ama me receipt?",
            "Mo wo special offers bi anaa?",
            "Mo wo nniama a me tumi ato de akai kuro yi anaa?",
            "Mo wo cini fie bi ben aha anaa?",
            "Mo wo clubs bi ben aha anaa?",
            "Wo te brofo kasa anaa?",
            "ATM machine no wo he?",
            // lodging questions, index 75 to 89
            "Manya obi de me nuoma no ako me dan nu mu anaa?",
            "Sen na me tumi aye reservation?",
            "Me tumi de me mmoa aba aha anaa?",
            "Me si den ekwa me booking no mu?",
            "Sen na me tumi atua meka wo ha?",
            "Mo ma towuro wo ha anaa?",
            "Menya iron anaa?",
            "Mo pene ma ye de atuo ba ha anaa?",
            "Mo horo nnuoma ma ahohowo anaa?",
            "Emere ben na mogye ahohowo?",
            "Me tumi aye camp fire anaa?",
            "Mo wo pack and play anaa?",
            "Menya dan aa me tumi ahye cigarette wo mu anaa?",
            "Menya dan aa yennhye cigarette wo mu anaa?",
            "Mo wo ndan ma sebi sebi ayare fuo?",
            // transportation questions, 90 to 104
            "Ehenfa na menya car a rent?",
            "Akwan ben na eye tiawa?",
            "Filling station ben na eben ha?",
            "Ehenfa na me tumi a tene tene me nan mu wo kwan no so?",
            "Wo be tumi aboa me na ma sesa me tyre no anaa?",
            "Eye sen?",
            "Emere ben mu na bus no ye adwuma?",
            "Okwantua yi be di mmere hyia sen?",
            "Asore ben na eben aha?",
            "Ewiemshen bea ben nae ben ha?",
            "Ehenfa na menya taxi?",
            "Ehenfa na menya helmet?",
            "Asore ben nae ben ha?",
            "Muslimii fuo som bea ben na eben ha?",
            "Emere ben na keteke ye adwuma wo ha?",
    };

    private static String Arabic [] = {
            // Airport questions, index 0 to 14
            "هل هناك مكوك مطار؟",
            "أين يمكنني العثور على ماكينة الصراف الآلي؟",
            "هل تتكلم اللغة الإنجليزية؟",
            "هل يمكنني استخدام هاتفك؟",
            "أين يمكنني أن أجد سيارة أجرة؟",
            "أين يمكنني شراء بطاقة sim؟",
            "أين يمكنني أن أجد مكتب فوركس؟",
            "هل يمكنك مساعدتي في العثور على متحدث اللغة الإنجليزية؟",
            "هل يوجد فندق لهذا المطار؟",
            "أين الخدمة الطبية؟",
            "أين المطالبة بالأمتعة؟",
            "أين هو الحمام؟",
            "أين محل بيع الهدايا؟",
            "أين خدمة العملاء؟",
            "أين العداد الرئيسي؟",
            // Emergency questions, index 15 to 29
            "ما هو عدد الشرطة؟",
            "هل يمكنك مساعدتي في الاتصال بالأمن؟",
            "أين أقرب مستشفى؟",
            "ما هو رقم EMT المحلي هنا؟",
            "أين أقرب مركز شرطة؟",
            "أين أقرب صيدلية؟",
            "أين يمكنني استئجار سيارة في المنطقة؟",
            "هل لديك أي نوع من الحساسية؟",
            "هل يمكنك الاتصال بي بسيارة إسعاف؟",
            "أين هو الحمام؟",
            "هل يمكنك أن تريني على التطبيق؟",
            "أنا تائه ، هل يمكنك مساعدتي من فضلك؟",
            "هل تتكلم اللغة الإنجليزية؟",
            "هل يمكنك التحدث بشكل أبطأ؟",
            "هل توجد صيدلية على مدار الساعة طوال أيام الأسبوع في المنطقة؟",
            // Food questions, index 30 to 44
            "أين يمكنني تناول وجبة الإفطار؟",
            "ما نوع الطعام الذي لديك؟",
            "هل لديك خيارات نباتية؟",
            "ما هو أقرب مطعم؟",
            "هل تقبل العملات الأجنبية؟",
            "يمكنك تقديم؟",
            "أين يمكنني الحصول على المطبخ الصيني؟",
            "هل لديك عروض خاصة؟",
            "ما هي خيارات السمك الخاصة بك؟",
            "هل يوجد جهاز صراف آلي في الجوار؟",
            "أين يمكنني شراء أغذية الأطفال",
            "أين يمكنني شراء الفواكه؟",
            "هل لديك بيض؟",
            "أين يمكنني شراء القدور والمقالي؟",
            "ما هي خيارات الحلوى الخاصة بك؟",
            // health questions, index 45 to 59
            "يمكنك تكلم الإنجليزية؟",
            "ما أقرب مستشفى حولك؟",
            "هل يوجد جهاز صراف آلي هنا؟",
            "هل لديك طبيب هنا؟",
            "هل يوجد طبيب حول؟",
            "أين يمكنني رؤية طبيب أطفال؟",
            "أين يمكنني الحصول على عدسات لاصقة؟",
            "هل هناك خدمة إسعاف؟",
            "أين أقرب صيدلية؟",
            "هل تأخذ بطاقات الائتمان؟",
            "أين أقرب مركز طوارئ؟",
            "أين يمكنني شراء الدواء؟",
            "هل يمكنك مساعدتي في الاتصال بالطبيب؟",
            "هل هناك هدية بصرية؟",
            "أين أدف؟",
            // leisure questions, index 60 to 74
            "أين يمكنني الحصول على دليل؟",
            "هل يوجد متحف حولها؟",
            "هل يوجد معرض حولها؟",
            "أين أقرب مركز تسوق؟",
            "ما هي أماكن الجذب؟",
            "أين يمكنني أن أجد سيارة أجرة؟",
            "هل هناك شواطئ في الجوار؟",
            "أين أقرب منتجع صحي؟",
            "هل يمكنني الحصول على الإيصال؟",
            "هل لديك أي عروض خاصة؟",
            "من أين أحصل على هدايا تذكارية هنا؟",
            "أين أقرب سينما؟",
            "ما هي النوادي الموجودة هنا؟",
            "هل تتكلم اللغة الإنجليزية؟",
            "أين آلة الصراف الآلي؟",
            // lodging questions, index 75 to 89
            "هل يمكنني الحصول على بواب؟",
            "كيف أقوم بالحجز؟",
            "هل تقبل الحيوانات الأليفة؟",
            "ما هي سياسة الإلغاء الخاصة بك؟",
            "ما هي سياسة الدفع الخاصة بك؟",
            "هل تقدم مناشف؟",
            "هل يمكنني الحصول على مكواة؟",
            "ما هي سياسة الأسلحة النارية الخاصة بك؟",
            "هل لديك خدمة غسيل الملابس؟",
            "ما هي أوقات تسجيل الوصول / المغادرة؟",
            "هل يمكنني أن أشعل نار المخيم؟",
            "هل الحزمة والمسرحيات متوفرة؟",
            "هل يمكنني الحصول على غرفة تدخين؟",
            "هل يمكنني الحصول على غرفة لغير المدخنين؟",
            "هل توجد غرف مجهزة لذوي الاحتياجات الخاصة؟",
            // transportation questions, 90 to 104
            "أين يمكنني استئجار سيارة؟",
            "ما أسرع طريق للاستخدام؟",
            "أين أقرب محطة تعبئة؟",
            "أين أقرب موقف راحة؟",
            "هل يمكنك مساعدتي في تغيير إطار؟",
            "كم هو الأجرة؟",
            "هل يمكنني الحصول على جدول الحافلات؟",
            "كم ستستغرق هذه الرحلة؟",
            "أين أقرب كنيس؟",
            "أين أقرب مطار؟",
            "أين يمكنني الحصول على سيارة أجرة؟",
            "هل يمكنني الحصول على خوذة؟",
            "أين أقرب كنيسة؟",
            "أين أقرب مسجد؟",
            "هل يمكنني الحصول على جدول القطار؟",
    };

}
